// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetMakerHubBack.API.Data;

#nullable disable

namespace ProjetMakerHubBack.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215132100_AddImageUrl")]
    partial class AddImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SearchName")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9433),
                            Name = "Pâtes",
                            SearchName = "pates"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9441),
                            Name = "Riz",
                            SearchName = "riz"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9447),
                            Name = "Semoule",
                            SearchName = "semoule"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9452),
                            Name = "Poulet",
                            SearchName = "poulet"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9458),
                            Name = "Thon",
                            SearchName = "thon"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9464),
                            Name = "Oeufs",
                            SearchName = "oeufs"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9469),
                            Name = "Tomates",
                            SearchName = "tomates"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9475),
                            Name = "Oignon",
                            SearchName = "oignon"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9480),
                            Name = "Ail",
                            SearchName = "ail"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9486),
                            Name = "Poivron",
                            SearchName = "poivron"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9491),
                            Name = "Carotte",
                            SearchName = "carotte"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9493),
                            Name = "Courgette",
                            SearchName = "courgette"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9501),
                            Name = "Champignons",
                            SearchName = "champignons"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9507),
                            Name = "Huile d'olive",
                            SearchName = "huiledolive"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9514),
                            Name = "Beurre",
                            SearchName = "beurre"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9519),
                            Name = "Crème",
                            SearchName = "creme"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9525),
                            Name = "Lait",
                            SearchName = "lait"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9530),
                            Name = "Parmesan",
                            SearchName = "parmesan"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9535),
                            Name = "Mozzarella",
                            SearchName = "mozzarella"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9541),
                            Name = "Pesto",
                            SearchName = "pesto"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9546),
                            Name = "Sauce tomate",
                            SearchName = "saucetomate"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9552),
                            Name = "Sel",
                            SearchName = "sel"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9557),
                            Name = "Poivre",
                            SearchName = "poivre"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9563),
                            Name = "Paprika",
                            SearchName = "paprika"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9569),
                            Name = "Cumin",
                            SearchName = "cumin"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9574),
                            Name = "Citron",
                            SearchName = "citron"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9579),
                            Name = "Miel",
                            SearchName = "miel"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000028"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9584),
                            Name = "Haricots rouges",
                            SearchName = "haricotsrouges"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000029"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9589),
                            Name = "Maïs",
                            SearchName = "mais"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 702, DateTimeKind.Utc).AddTicks(9594),
                            Name = "Salade",
                            SearchName = "salade"
                        });
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.PantryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserId");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.PlanSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Portion")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("PlanSlots");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasePortion")
                        .HasColumnType("int");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            BasePortion = 2,
                            CookTime = 10,
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 716, DateTimeKind.Utc).AddTicks(4349),
                            CreatedByUserId = new Guid("62d01393-e0d0-4e0a-ad38-6e8507c4fcc2"),
                            Description = "Classique rapide et efficace.",
                            IsPublic = true,
                            PrepTime = 5,
                            Title = "Pâtes au pesto"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            BasePortion = 2,
                            CookTime = 15,
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 716, DateTimeKind.Utc).AddTicks(4363),
                            CreatedByUserId = new Guid("62d01393-e0d0-4e0a-ad38-6e8507c4fcc2"),
                            Description = "Parfait pour écouler le frigo.",
                            IsPublic = true,
                            PrepTime = 10,
                            Title = "Riz sauté au poulet"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            BasePortion = 1,
                            CookTime = 8,
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 716, DateTimeKind.Utc).AddTicks(4373),
                            CreatedByUserId = new Guid("62d01393-e0d0-4e0a-ad38-6e8507c4fcc2"),
                            Description = "Simple, rapide, protéinée.",
                            IsPublic = true,
                            PrepTime = 5,
                            Title = "Omelette champignons-fromage"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            BasePortion = 2,
                            CookTime = 0,
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 716, DateTimeKind.Utc).AddTicks(4382),
                            CreatedByUserId = new Guid("da32c7e3-2ff5-4bd0-9b2b-e407cdc36df4"),
                            Description = "Healthy et frais.",
                            IsPublic = true,
                            PrepTime = 10,
                            Title = "Salade thon maïs citron"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            BasePortion = 3,
                            CookTime = 20,
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 716, DateTimeKind.Utc).AddTicks(4392),
                            CreatedByUserId = new Guid("da32c7e3-2ff5-4bd0-9b2b-e407cdc36df4"),
                            Description = "Version simple sans prise de tête.",
                            IsPublic = true,
                            PrepTime = 10,
                            Title = "Chili rapide"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            BasePortion = 2,
                            CookTime = 15,
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 716, DateTimeKind.Utc).AddTicks(4401),
                            CreatedByUserId = new Guid("da32c7e3-2ff5-4bd0-9b2b-e407cdc36df4"),
                            Description = "Sucré-salé facile.",
                            IsPublic = true,
                            PrepTime = 10,
                            Title = "Poulet miel-citron"
                        });
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BaseQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuantityText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Unit")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            BaseQuantity = 200m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000020"),
                            BaseQuantity = 60m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000018"),
                            BaseQuantity = 20m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            BaseQuantity = 200m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            BaseQuantity = 200m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000008"),
                            BaseQuantity = 1m,
                            Unit = 5
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000009"),
                            BaseQuantity = 1m,
                            Unit = 5
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000006"),
                            BaseQuantity = 3m,
                            Unit = 5
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000013"),
                            BaseQuantity = 150m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000019"),
                            BaseQuantity = 80m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000030"),
                            BaseQuantity = 1m,
                            QuantityText = "1 bol",
                            Unit = 5
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000005"),
                            BaseQuantity = 160m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000029"),
                            BaseQuantity = 120m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000026"),
                            BaseQuantity = 1m,
                            Unit = 5
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000008"),
                            BaseQuantity = 1m,
                            Unit = 5
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000010"),
                            BaseQuantity = 1m,
                            Unit = 5
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000021"),
                            BaseQuantity = 300m,
                            Unit = 3
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000028"),
                            BaseQuantity = 240m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000029"),
                            BaseQuantity = 120m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000025"),
                            QuantityText = "1 c.à.c",
                            Unit = 0
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            BaseQuantity = 250m,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000027"),
                            BaseQuantity = 1m,
                            Unit = 7
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("b0000000-0000-0000-0000-000000000026"),
                            BaseQuantity = 1m,
                            Unit = 5
                        });
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StepInstruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            StepInstruction = "Cuire les pâtes dans l'eau salée.",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            StepInstruction = "Égoutter, ajouter le pesto et mélanger.",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            StepInstruction = "Faire revenir oignon et ail dans l'huile.",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            StepInstruction = "Ajouter le poulet, cuire puis ajouter le riz et assaisonner.",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            StepInstruction = "Battre les œufs avec sel et poivre.",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000006"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            StepInstruction = "Cuire les champignons, ajouter les œufs et le fromage.",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000007"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            StepInstruction = "Mélanger salade, thon et maïs.",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000008"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            StepInstruction = "Assaisonner avec citron, huile d'olive, sel et poivre.",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000009"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            StepInstruction = "Faire revenir oignon et poivron.",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000010"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            StepInstruction = "Ajouter sauce tomate, haricots, maïs et épices, mijoter.",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000011"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            StepInstruction = "Faire dorer le poulet dans un peu d'huile.",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000012"),
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            StepInstruction = "Ajouter miel + citron, laisser réduire et assaisonner.",
                            StepNumber = 2
                        });
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuantityText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ShoppingListId", "IngredientId", "Unit")
                        .IsUnique();

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Végétarien",
                            SearchName = "vegetarien"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Vegan",
                            SearchName = "vegan"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Sans gluten",
                            SearchName = "sansgluten"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Name = "Sans lactose",
                            SearchName = "sanslactose"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Name = "Healthy",
                            SearchName = "healthy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Name = "Protéiné",
                            SearchName = "proteine"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Name = "Rapide",
                            SearchName = "rapide"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Name = "Facile",
                            SearchName = "facile"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Name = "Express",
                            SearchName = "express"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Name = "Batch cooking",
                            SearchName = "batchcooking"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            Name = "Entrée",
                            SearchName = "entree"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            Name = "Plat principal",
                            SearchName = "platprincipal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            Name = "Dessert",
                            SearchName = "dessert"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Name = "Petit-déjeuner",
                            SearchName = "petitdejeuner"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Name = "Apéritif",
                            SearchName = "aperitif"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Name = "Italien",
                            SearchName = "italien"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Name = "Asiatique",
                            SearchName = "asiatique"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Name = "Mexicain",
                            SearchName = "mexicain"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Name = "Traditionnel",
                            SearchName = "traditionnel"
                        });
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da32c7e3-2ff5-4bd0-9b2b-e407cdc36df4"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 722, DateTimeKind.Utc).AddTicks(4956),
                            DisplayName = "Kooz",
                            Email = "kooz@mail.com",
                            PasswordHash = "1b813899-603a-40cf-a635-c56ef6363ca52sQKF7IwePtw1OwhdieKiZNTz7nsk3R7x6lnvoBUCQeW0L7DRSMGnLd0TdjxiDCKwvSJgbHZqMnSaQH5nFsZDw==",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("62d01393-e0d0-4e0a-ad38-6e8507c4fcc2"),
                            CreatedAt = new DateTime(2026, 2, 15, 13, 20, 58, 722, DateTimeKind.Utc).AddTicks(5249),
                            DisplayName = "Usertest",
                            Email = "usertest@mail.com",
                            PasswordHash = "4988d3e3-2a76-48df-8a8f-d7353ac9811eq6ubEYi/cX9Zqf0Y7vQk3tR1rwn58Z0OFeP9sOIOg3AvkY9QA/eHAH2RHNw8OA+lBLhIWqFpRuuaKPpFBYydBQ==",
                            Role = 1
                        });
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.UserRecipe", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserRecipes");
                });

            modelBuilder.Entity("RecipeTags", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111126")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111117")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111118")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111127")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111118")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111116")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111117")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111117")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111128")
                        },
                        new
                        {
                            RecipeId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            TagId = new Guid("11111111-1111-1111-1111-111111111118")
                        });
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.PantryItem", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("PantryItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetMakerHubBack.Domain.Entities.User", "User")
                        .WithMany("PantryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Plan", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.User", "User")
                        .WithMany("Plans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.PlanSlot", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Plan", "Plan")
                        .WithMany("Slots")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Recipe", "Recipe")
                        .WithMany("PlanSlots")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Plan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.RecipeStep", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.ShoppingList", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.User", "User")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetMakerHubBack.Domain.Entities.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.UserRecipe", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Recipe", "Recipe")
                        .WithMany("UserRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetMakerHubBack.Domain.Entities.User", "User")
                        .WithMany("UserRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeTags", b =>
                {
                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetMakerHubBack.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("PantryItems");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("PlanSlots");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeSteps");

                    b.Navigation("UserRecipes");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("ProjetMakerHubBack.Domain.Entities.User", b =>
                {
                    b.Navigation("PantryItems");

                    b.Navigation("Plans");

                    b.Navigation("Recipes");

                    b.Navigation("ShoppingLists");

                    b.Navigation("UserRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
